server:
    error:
        include-message: always
        include-binding-errors: always

spring.datasource.url=jdbc:mysql://localhost:3305/barangay_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true